N/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

account/urls.py
from django.urls import path
from . import views


app_name = "account"
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
]

home/urls.py
from . import views
from django.urls import path


app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('posts/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('posts/write/', views.PostWriteView.as_view(), name='post_write'),
    path('posts/like/<int:post_id>', views.PostLikeView.as_view(), name='post_like'),
    path('reply/<int:post_id>/<int:comment_id>/', views.ReplyWriteView.as_view(), name='reply_write'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    body = models.TextField()
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta():
        ordering = ['-created']


    def __str__(self):
        return f'{self.slug} - {self.created}'
    
    def get_absolute_url(self):
        return reverse("home:post_detail", args=[self.id, self.slug])
    

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomment')
    body = models.TextField(max_length=400)
    created = models.DateTimeField(auto_now_add=True)
    replied_to = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomment', null=True, blank=True)
    is_reply = models.BooleanField(default=False)

    class Meta():
        ordering = ['-created']

    def __str__(self):
        return f'{self.user} - {self.body[:20]}'


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvotes')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvotes')


    def __str__(self):
        return f'{self.user} liked {self.post.slug}'
    

home/forms.py
from django import forms
from .models import Post, Comment


class PostWriteUpdateForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ['body']


class CommentWriteForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control'})
        }


class ReplyWriteForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ['body']
        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control'})
        }


class PostSearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from .models import Post, Comment, Vote
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostWriteUpdateForm, CommentWriteForm, ReplyWriteForm, PostSearchForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class HomeView(View):
    class_form = PostSearchForm

    def get(self, request):
        posts = Post.objects.all()
        if request.GET.get('search'):
            posts = posts.filter(body__contains=request.GET['search'])
        return render(request, 'home/index.html', {'posts':posts, 'form':self.class_form})


class PostDetailView(View):
    form_class = CommentWriteForm
    form_class_reply = ReplyWriteForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.post_instance
        comments = post.pcomment.filter(is_reply=False)
        return render(request, 'home/post_detail.html', {'post':self.post_instance, 'comments':comments, 'form':self.form_class, 'reply_form':self.form_class_reply})
    
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid:
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'Your comment is up!', 'success')
            return redirect('home:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, requset, post_id):
        post = Post.objects.get(pk=post_id)
        post_author_id = post.user.id
        if post.user.id == requset.user.id:
            post.delete()
            messages.success(requset, 'Post Deleted Successfully', 'success')
        else:
            messages.error(requset, 'You DONT own this Post', 'danger')
        return redirect('account:user_profile', post_author_id)
    

class PostUpdateView(LoginRequiredMixin, View):
    form_class = PostWriteUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if post.user.id != request.user.id:
            messages.error(request, 'You are NOT the author of this post', 'danger')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, post_id):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'home/post_update.html', {'form':form})
    
    def post(self, request, post_id):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            updated_post = form.save(commit=False)
            updated_post.slug = slugify(form.cleaned_data['body'][:30])
            updated_post.save()
            messages.success(request, 'Post Updated!', 'success')
            return redirect('home:post_detail', post.id, post.slug)
        


class PostWriteView(LoginRequiredMixin, View):
    form_class = PostWriteUpdateForm


    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, 'home/post_write.html', {'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.slug = slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'Post Submitted Successfully!', 'success')
            return redirect('home:post_detail', new_post.id, new_post.slug)
        


class ReplyWriteView(LoginRequiredMixin, View):
    form_class = ReplyWriteForm

    def post(self, request, post_id, comment_id):
        form = self.form_class(request.POST)
        post = get_object_or_404(Post, pk=post_id)
        comment = get_object_or_404(Comment, pk=comment_id)
        if form.is_valid():
            new_reply = form.save(commit=False)
            new_reply.user = request.user
            new_reply.post = post
            new_reply.replied_to = comment
            new_reply.is_reply = True
            new_reply.save()
            messages.success(request, 'Your reply submitted', 'success')
        return redirect('home:post_detail', post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, pk=kwargs['post_id'])
        user = request.user
        if Vote.objects.filter(post=post, user=user).exists():
            messages.error(request, 'Liked This Post already!', 'warning')
            return redirect('home:post_detail', post.id, post.slug)
        
        Vote.objects.create(post=post, user=user)
        messages.success(request, 'Liked!', 'success')
        return redirect('home:post_detail', post.id, post.slug)

home/templates/home/index.html
{% extends "base.html" %}
{% block content %}

    <form action='' method='GET' class='col-md-3' novalidate>
        {{ form.as_p }}
        <input class="btn btn-outline-primary" type='submit' value='Search'>
    </form>
    <br/>
    <div class='card'>
        {% for pst in posts %}
            <a href='{{ pst.get_absolute_url }}' class='card-body'>
                <h5 class='card-title'>{{ pst.body|truncatewords:8 }}</h5>
                <small>{{ pst.user.username }}</small>
            </a>
            
        {% endfor %}
        <div class="card-footer text-muted">
            2 days ago
        </div>
    </div>
{% endblock content %}

home/templates/home/post_detail.html
{% extends "base.html" %}
{% block content %}
    <a href='{% url 'account:user_profile' post.user.id %}'>{{ post.user.username }}</a>
    <small>{{ post.updated|date:"h:iA | M-d-Y" }}</small>
    <hr>
    <p class='card-body'>{{ post.body }}</p>
    {% if post.user.id == request.user.id %}
        <a href='{% url 'home:post_delete' post.id %}' class='btn btn-outline-danger' >Delete</a>
        <a href='{% url 'home:post_update' post.id %}' class='btn btn-outline-dark' >Update</a>
    {% endif %}
    <hr>

    {% if user.is_authenticated %}
        <a href='{% url 'home:post_like' post.id %}' class='btn btn-primary col-md-2'>Like</a>
        <form action='' method='POST' novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-outline-dark" type="submit" value="Send Comment">
        </form>
        <br>
    {% endif %}

    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }} ago</p>
            <p class="card-body">{{ comment.body }}</p>
        
            {% if user.is_authenticated %}
                <form action='{% url 'home:reply_write' post.id comment.id %}' method='POST' novalidate class='w-25 h-25 m-2 p-2'>
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input class="btn btn-outline-light" type="submit" value="Send Reply">
                </form>
            {% endif %}
            
            <br>
            {% with replies=comment.rcomment.all %}
                {% for reply in replies %}
                    <p class='bg-primary m-2 p-2'>{{ reply.user }} | {{ reply.created|timesince }} <br> {{ reply.body }}</p>

                {% endfor %}
            {% endwith %}
        </div>
        <br>
    {% empty %}
        <p>No commens yet!</p>
    {% endfor %}



{% endblock content %}

home/templates/home/post_update.html
{% extends "base.html" %}
{% block content %}
    <form action='' method='POST' novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary" type="submit" value="Update">
    </form>
{% endblock content %}

home/templates/home/post_write.html
{% extends "base.html" %}
{% block content %}
    <form action='' method='POST' novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-outline-dark" type="submit" value="Submit">
    </form>
{% endblock content %}