N/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
]

account/urls.py
from django.urls import path
from . import views


app_name = "account"
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
]

home/urls.py
from . import views
from django.urls import path


app_name = "home"
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('posts/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('posts/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('posts/write/', views.PostWriteView.as_view(), name='post_write'),
    path('posts/like/<int:post_id>', views.PostLikeView.as_view(), name='post_like'),
    path('reply/<int:post_id>/<int:comment_id>/', views.ReplyWriteView.as_view(), name='reply_write'),
]

templates/incs/messages.html
{% if messages %}
    
    {% for msg in messages %}
        <p class='alert alert-{{ msg.tags }} col-md-3 ' > {{msg}} </p>
    {% endfor %}

{% endif %}

templates/incs/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url "home:home" %}">Social</a>
        {% if request.user.is_authenticated %}
          <a class="navbar-brand" href="{% url "account:user_profile" request.user.id %}">{{ request.user.username }}'s</a>
          {% comment %} <a class="navbar-brand" href="{% url "account:user_logout" %}">Logout</a>
          <a href='{% url 'home:post_write' %}' class='btn btn-outline-light'>Write</a> {% endcomment %}
        {% else %}
          <a class="navbar-brand" href="{% url "account:user_register" %}">Register</a>
          <a class="navbar-brand" href="{% url "account:user_login" %}">Login</a>
        {% endif %}
      </div>
    </div>
  </nav>